name: Test and Release

env:
  MAIN_REF: refs/heads/master

on:
  push:
    branches: ["**"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test-and-release:
    name: Test and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.17
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm dev:prepare && pnpm prepack

      - name: Test
        run: pnpm test

      - name: Capture new release versions
        if: ${{ github.ref == env.MAIN_REF }}
        run: |
          if pnpx @changesets/cli status --output=release.json; then
            echo "CHANGED_PACKAGES=$(jq -r '.releases | map(.newVersion) | join(", ")' release.json)" >> "$GITHUB_ENV"
            rm release.json
          fi

      - name: Create Release Pull Request or Publish to npm
        if: ${{ github.ref == env.MAIN_REF }}
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
          title: "Release version ${{env.CHANGED_PACKAGES}}"
          commit: "Release version ${{env.CHANGED_PACKAGES}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
